//
// This source file is part of the Grove FHIR open-source project
//
// SPDX-FileCopyrightText: 2026 Schmiedmayer Lab and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
// GENERATED FILE. Edit the adapter catalog and run
// `python3 Scripts/render-adapter-source-terminology.py`.
//

CodeSystem: HealthKitSourceTypeCS
Id: healthkit-source-type
Title: "HealthKit Source Types"
Description: "The complete closed HealthKit platform source-type inventory frozen by version 0.2.0. A coding preserves exact source semantics and does not replace the shared or standard clinical coding."
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* ^copyright = "HealthKit API identifiers and type names originate from Apple Inc. and are used here only to identify source API concepts for interoperability. The MIT license applies to Grove-authored definitions; it does not grant rights in Apple material."
* #HKCategoryTypeIdentifierAbdominalCramps "Abdominal Cramps"
* #HKCategoryTypeIdentifierAcne "Acne"
* #HKCategoryTypeIdentifierAppetiteChanges "Appetite Changes"
* #HKCategoryTypeIdentifierAppleStandHour "Apple Stand Hour"
* #HKCategoryTypeIdentifierAppleWalkingSteadinessEvent "Apple Walking Steadiness Event"
* #HKCategoryTypeIdentifierAudioExposureEvent "Audio Exposure Event (Deprecated)"
* #HKCategoryTypeIdentifierBladderIncontinence "Bladder Incontinence"
* #HKCategoryTypeIdentifierBleedingAfterMenopause "Bleeding After Menopause"
* #HKCategoryTypeIdentifierBleedingAfterPregnancy "Bleeding After Pregnancy"
* #HKCategoryTypeIdentifierBleedingDuringPregnancy "Bleeding During Pregnancy"
* #HKCategoryTypeIdentifierBloating "Bloating"
* #HKCategoryTypeIdentifierBreastPain "Breast Pain"
* #HKCategoryTypeIdentifierCervicalMucusQuality "Cervical Mucus Quality"
* #HKCategoryTypeIdentifierChestTightnessOrPain "Chest Tightness/Pain"
* #HKCategoryTypeIdentifierChills "Chills"
* #HKCategoryTypeIdentifierConstipation "Constipation"
* #HKCategoryTypeIdentifierContraceptive "Contraceptive"
* #HKCategoryTypeIdentifierCoughing "Coughing"
* #HKCategoryTypeIdentifierDiarrhea "Diarrhea"
* #HKCategoryTypeIdentifierDizziness "Dizziness"
* #HKCategoryTypeIdentifierDrySkin "Dry Skin"
* #HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent "Environmental Audio Exposure Event"
* #HKCategoryTypeIdentifierFainting "Fainting"
* #HKCategoryTypeIdentifierFatigue "Fatigue"
* #HKCategoryTypeIdentifierFever "Fever"
* #HKCategoryTypeIdentifierGeneralizedBodyAche "Generalized Body Ache"
* #HKCategoryTypeIdentifierHairLoss "Hair Loss"
* #HKCategoryTypeIdentifierHandwashingEvent "Handwashing Event"
* #HKCategoryTypeIdentifierHeadache "Headache"
* #HKCategoryTypeIdentifierHeadphoneAudioExposureEvent "Headphone Audio Exposure Event"
* #HKCategoryTypeIdentifierHeartburn "Heartburn"
* #HKCategoryTypeIdentifierHighHeartRateEvent "High Heart Rate Event"
* #HKCategoryTypeIdentifierHotFlashes "Hot Flashes"
* #HKCategoryTypeIdentifierHypertensionEvent "Hypertension Event"
* #HKCategoryTypeIdentifierInfrequentMenstrualCycles "Infrequent Menstrual Cycles"
* #HKCategoryTypeIdentifierIntermenstrualBleeding "Intermenstrual Bleeding"
* #HKCategoryTypeIdentifierIrregularHeartRhythmEvent "Irregular Heart Rhythm Event"
* #HKCategoryTypeIdentifierIrregularMenstrualCycles "Irregular Menstrual Cycles"
* #HKCategoryTypeIdentifierLactation "Lactation"
* #HKCategoryTypeIdentifierLossOfSmell "Loss of Smell"
* #HKCategoryTypeIdentifierLossOfTaste "Loss of Taste"
* #HKCategoryTypeIdentifierLowCardioFitnessEvent "Low Cardio Fitness Event"
* #HKCategoryTypeIdentifierLowHeartRateEvent "Low Heart Rate Event"
* #HKCategoryTypeIdentifierLowerBackPain "Lower Back Pain"
* #HKCategoryTypeIdentifierMemoryLapse "Memory Lapse"
* #HKCategoryTypeIdentifierMenopausalState "Menopausal State"
* #HKCategoryTypeIdentifierMenstrualFlow "Menstrual Flow"
* #HKCategoryTypeIdentifierMindfulSession "Mindful Session"
* #HKCategoryTypeIdentifierMoodChanges "Mood Changes"
* #HKCategoryTypeIdentifierNausea "Nausea"
* #HKCategoryTypeIdentifierNightSweats "Night Sweats"
* #HKCategoryTypeIdentifierOvulationTestResult "Ovulation Test Result"
* #HKCategoryTypeIdentifierPelvicPain "Pelvic Pain"
* #HKCategoryTypeIdentifierPersistentIntermenstrualBleeding "Persistent Intermenstrual Bleeding"
* #HKCategoryTypeIdentifierPregnancy "Pregnancy"
* #HKCategoryTypeIdentifierPregnancyTestResult "Pregnancy Test Result"
* #HKCategoryTypeIdentifierProgesteroneTestResult "Progesterone Test Result"
* #HKCategoryTypeIdentifierProlongedMenstrualPeriods "Prolonged Menstrual Periods"
* #HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat "Rapid/Pounding/Fluttering Heartbeat"
* #HKCategoryTypeIdentifierRunnyNose "Runny Nose"
* #HKCategoryTypeIdentifierSexualActivity "Sexual Activity"
* #HKCategoryTypeIdentifierShortnessOfBreath "Shortness of Breath"
* #HKCategoryTypeIdentifierSinusCongestion "Sinus Congestion"
* #HKCategoryTypeIdentifierSkippedHeartbeat "Skipped Heartbeat"
* #HKCategoryTypeIdentifierSleepAnalysis "Sleep Analysis"
* #HKCategoryTypeIdentifierSleepApneaEvent "Sleep Apnea Event"
* #HKCategoryTypeIdentifierSleepChanges "Sleep Changes"
* #HKCategoryTypeIdentifierSoreThroat "Sore Throat"
* #HKCategoryTypeIdentifierToothbrushingEvent "Toothbrushing Event"
* #HKCategoryTypeIdentifierVaginalDryness "Vaginal Dryness"
* #HKCategoryTypeIdentifierVomiting "Vomiting"
* #HKCategoryTypeIdentifierWheezing "Wheezing"
* #HKClinicalTypeIdentifierAllergyRecord "Allergy Record"
* #HKClinicalTypeIdentifierClinicalNoteRecord "Clinical Note Record"
* #HKClinicalTypeIdentifierConditionRecord "Condition Record"
* #HKClinicalTypeIdentifierCoverageRecord "Coverage Record"
* #HKClinicalTypeIdentifierImmunizationRecord "Immunization Record"
* #HKClinicalTypeIdentifierLabResultRecord "Lab Result Record"
* #HKClinicalTypeIdentifierMedicationRecord "Medication Record"
* #HKClinicalTypeIdentifierProcedureRecord "Procedure Record"
* #HKClinicalTypeIdentifierVitalSignRecord "Vital Sign Record"
* #HKCorrelationTypeIdentifierBloodPressure "Blood Pressure"
* #HKCorrelationTypeIdentifierFood "Food"
* #HKDataTypeIdentifierAudiogram "Audiogram"
* #HKDataTypeIdentifierElectrocardiogram "ECG"
* #HKDataTypeIdentifierHeartbeatSeries "Heartbeat Series"
* #HKDataTypeStateOfMind "State of Mind"
* #HKQuantityTypeIdentifierActiveEnergyBurned "Active Energy Burned"
* #HKQuantityTypeIdentifierAppleExerciseTime "Apple Exercise Time"
* #HKQuantityTypeIdentifierAppleMoveTime "Apple Move Time"
* #HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances "Apple Sleeping Breathing Disturbances"
* #HKQuantityTypeIdentifierAppleSleepingWristTemperature "Apple Sleeping Wrist Temperature"
* #HKQuantityTypeIdentifierAppleStandTime "Apple Stand Time"
* #HKQuantityTypeIdentifierAppleWalkingSteadiness "Apple Walking Steadiness"
* #HKQuantityTypeIdentifierAtrialFibrillationBurden "AFib Burden"
* #HKQuantityTypeIdentifierBasalBodyTemperature "Basal Body Temperature"
* #HKQuantityTypeIdentifierBasalEnergyBurned "Basal Energy Burned"
* #HKQuantityTypeIdentifierBloodAlcoholContent "Blood Alcohol Content"
* #HKQuantityTypeIdentifierBloodGlucose "Blood Glucose"
* #HKQuantityTypeIdentifierBloodPressureDiastolic "Blood Pressure (Diastolic)"
* #HKQuantityTypeIdentifierBloodPressureSystolic "Blood Pressure (Systolic)"
* #HKQuantityTypeIdentifierBodyFatPercentage "Body Fat Percentage"
* #HKQuantityTypeIdentifierBodyMass "Body Mass"
* #HKQuantityTypeIdentifierBodyMassIndex "BMI"
* #HKQuantityTypeIdentifierBodyTemperature "Body Temperature"
* #HKQuantityTypeIdentifierCrossCountrySkiingSpeed "Cross Country Skiing Speed"
* #HKQuantityTypeIdentifierCyclingCadence "Cycling Cadence"
* #HKQuantityTypeIdentifierCyclingFunctionalThresholdPower "Cycling Functional Threshold Power"
* #HKQuantityTypeIdentifierCyclingPower "Cycling Power"
* #HKQuantityTypeIdentifierCyclingSpeed "Cycling Speed"
* #HKQuantityTypeIdentifierDietaryBiotin "Dietary Biotin Intake"
* #HKQuantityTypeIdentifierDietaryCaffeine "Dietary Caffeine Intake"
* #HKQuantityTypeIdentifierDietaryCalcium "Dietary Calcium Intake"
* #HKQuantityTypeIdentifierDietaryCarbohydrates "Dietary Carbohydrates Intake"
* #HKQuantityTypeIdentifierDietaryChloride "Dietary Chloride Intake"
* #HKQuantityTypeIdentifierDietaryCholesterol "Dietary Cholesterol Intake"
* #HKQuantityTypeIdentifierDietaryChromium "Dietary Chromium Intake"
* #HKQuantityTypeIdentifierDietaryCopper "Dietary Copper Intake"
* #HKQuantityTypeIdentifierDietaryEnergyConsumed "Dietary Energy Consumed"
* #HKQuantityTypeIdentifierDietaryFatMonounsaturated "Dietary Monounsaturated Fat Intake"
* #HKQuantityTypeIdentifierDietaryFatPolyunsaturated "Dietary Polyunsaturated Fat Intake"
* #HKQuantityTypeIdentifierDietaryFatSaturated "Dietary Saturated Fat Intake"
* #HKQuantityTypeIdentifierDietaryFatTotal "Dietary Total Fat Intake"
* #HKQuantityTypeIdentifierDietaryFiber "Dietary Fiber Intake"
* #HKQuantityTypeIdentifierDietaryFolate "Dietary Folate Intake"
* #HKQuantityTypeIdentifierDietaryIodine "Dietary Iodine Intake"
* #HKQuantityTypeIdentifierDietaryIron "Dietary Iron Intake"
* #HKQuantityTypeIdentifierDietaryMagnesium "Dietary Magnesium Intake"
* #HKQuantityTypeIdentifierDietaryManganese "Dietary Manganese Intake"
* #HKQuantityTypeIdentifierDietaryMolybdenum "Dietary Molybdenum Intake"
* #HKQuantityTypeIdentifierDietaryNiacin "Dietary Niacin Intake"
* #HKQuantityTypeIdentifierDietaryPantothenicAcid "Dietary Pantothenic Acid Intake"
* #HKQuantityTypeIdentifierDietaryPhosphorus "Dietary Phosphorus Intake"
* #HKQuantityTypeIdentifierDietaryPotassium "Dietary Potassium Intake"
* #HKQuantityTypeIdentifierDietaryProtein "Dietary Protein Intake"
* #HKQuantityTypeIdentifierDietaryRiboflavin "Dietary Riboflavin Intake"
* #HKQuantityTypeIdentifierDietarySelenium "Dietary Selenium Intake"
* #HKQuantityTypeIdentifierDietarySodium "Dietary Sodium Intake"
* #HKQuantityTypeIdentifierDietarySugar "Dietary Sugar Intake"
* #HKQuantityTypeIdentifierDietaryThiamin "Dietary Thiamin Intake"
* #HKQuantityTypeIdentifierDietaryVitaminA "Dietary Vitamin A Intake"
* #HKQuantityTypeIdentifierDietaryVitaminB12 "Dietary Vitamin B12 Intake"
* #HKQuantityTypeIdentifierDietaryVitaminB6 "Dietary Vitamin B6 Intake"
* #HKQuantityTypeIdentifierDietaryVitaminC "Dietary Vitamin C Intake"
* #HKQuantityTypeIdentifierDietaryVitaminD "Dietary Vitamin D Intake"
* #HKQuantityTypeIdentifierDietaryVitaminE "Dietary Vitamin E Intake"
* #HKQuantityTypeIdentifierDietaryVitaminK "Dietary Vitamin K Intake"
* #HKQuantityTypeIdentifierDietaryWater "Dietary Water Intake"
* #HKQuantityTypeIdentifierDietaryZinc "Dietary Zinc Intake"
* #HKQuantityTypeIdentifierDistanceCrossCountrySkiing "Cross-Country Skiing Distance"
* #HKQuantityTypeIdentifierDistanceCycling "Cycling Distance"
* #HKQuantityTypeIdentifierDistanceDownhillSnowSports "Downhill Snow Sports Distance"
* #HKQuantityTypeIdentifierDistancePaddleSports "Paddle Sports Distance"
* #HKQuantityTypeIdentifierDistanceRowing "Rowing Distance"
* #HKQuantityTypeIdentifierDistanceSkatingSports "Skating Sports Distance"
* #HKQuantityTypeIdentifierDistanceSwimming "Swimming Distance"
* #HKQuantityTypeIdentifierDistanceWalkingRunning "Distance Walking/Running"
* #HKQuantityTypeIdentifierDistanceWheelchair "Wheelchair Distance"
* #HKQuantityTypeIdentifierElectrodermalActivity "Electrodermal Activity"
* #HKQuantityTypeIdentifierEnvironmentalAudioExposure "Environmental Audio Exposure"
* #HKQuantityTypeIdentifierEnvironmentalSoundReduction "Environmental Sound Reduction"
* #HKQuantityTypeIdentifierEstimatedWorkoutEffortScore "Estimated Workout Effort"
* #HKQuantityTypeIdentifierFlightsClimbed "Flights Climbed"
* #HKQuantityTypeIdentifierForcedExpiratoryVolume1 "Forced Expiratory Volume (1 sec)"
* #HKQuantityTypeIdentifierForcedVitalCapacity "Forced Vital Capacity"
* #HKQuantityTypeIdentifierHeadphoneAudioExposure "Headphone Audio Exposure"
* #HKQuantityTypeIdentifierHeartRate "Heart Rate"
* #HKQuantityTypeIdentifierHeartRateRecoveryOneMinute "Heart Rate Recovery (1 min)"
* #HKQuantityTypeIdentifierHeartRateVariabilitySDNN "Heart Rate Variability SDNN"
* #HKQuantityTypeIdentifierHeight "Height"
* #HKQuantityTypeIdentifierInhalerUsage "Inhaler Usage"
* #HKQuantityTypeIdentifierInsulinDelivery "Insulin Delivery"
* #HKQuantityTypeIdentifierLeanBodyMass "Lean Body Mass"
* #HKQuantityTypeIdentifierNikeFuel "NikeFuel"
* #HKQuantityTypeIdentifierNumberOfAlcoholicBeverages "Number of Alcoholic Beverages"
* #HKQuantityTypeIdentifierNumberOfTimesFallen "Number of Times Fallen"
* #HKQuantityTypeIdentifierOxygenSaturation "Oxygen Saturation"
* #HKQuantityTypeIdentifierPaddleSportsSpeed "Paddle Sports Speed"
* #HKQuantityTypeIdentifierPeakExpiratoryFlowRate "Peak Expiratory Flow Rate"
* #HKQuantityTypeIdentifierPeripheralPerfusionIndex "Peripheral Perfusion Index"
* #HKQuantityTypeIdentifierPhysicalEffort "Physical Effort"
* #HKQuantityTypeIdentifierPushCount "Wheelchair Push Count"
* #HKQuantityTypeIdentifierRespiratoryRate "Respiratory Rate"
* #HKQuantityTypeIdentifierRestingHeartRate "Resting Heart Rate"
* #HKQuantityTypeIdentifierRowingSpeed "Rowing Speed"
* #HKQuantityTypeIdentifierRunningGroundContactTime "Ground Contact Time"
* #HKQuantityTypeIdentifierRunningPower "Running Power"
* #HKQuantityTypeIdentifierRunningSpeed "Running Speed"
* #HKQuantityTypeIdentifierRunningStrideLength "Running Stride Length"
* #HKQuantityTypeIdentifierRunningVerticalOscillation "Running Vertical Oscillation"
* #HKQuantityTypeIdentifierSixMinuteWalkTestDistance "6 Minute Walk Test Distance"
* #HKQuantityTypeIdentifierStairAscentSpeed "Stair Ascent Speed"
* #HKQuantityTypeIdentifierStairDescentSpeed "Stair Descent Speed"
* #HKQuantityTypeIdentifierStepCount "Step Count"
* #HKQuantityTypeIdentifierSwimmingStrokeCount "Swimming Stroke Count"
* #HKQuantityTypeIdentifierTimeInDaylight "Time in Daylight"
* #HKQuantityTypeIdentifierUVExposure "UV Exposure"
* #HKQuantityTypeIdentifierUnderwaterDepth "Underwater Depth"
* #HKQuantityTypeIdentifierVO2Max "VO2Max"
* #HKQuantityTypeIdentifierWaistCircumference "Waist Circumference"
* #HKQuantityTypeIdentifierWalkingAsymmetryPercentage "Walking Asymmetry Percentage"
* #HKQuantityTypeIdentifierWalkingDoubleSupportPercentage "Walking Double Support Percentage"
* #HKQuantityTypeIdentifierWalkingHeartRateAverage "Walking Heart Rate Average"
* #HKQuantityTypeIdentifierWalkingSpeed "Walking Speed"
* #HKQuantityTypeIdentifierWalkingStepLength "Walking Step Length"
* #HKQuantityTypeIdentifierWaterTemperature "Water Temperature"
* #HKQuantityTypeIdentifierWorkoutEffortScore "Workout Effort"
* #HKScoredAssessmentTypeIdentifierGAD7 "GAD-7"
* #HKScoredAssessmentTypeIdentifierPHQ9 "PHQ-9"
* #HKVisionPrescriptionTypeIdentifier "Vision Prescription"
* #HKWorkoutRouteTypeIdentifier "Workout Route"
* #HKWorkoutTypeIdentifier "Workout"

ValueSet: HealthKitSourceTypeVS
Id: healthkit-source-type
Title: "HealthKit Source Types"
Description: "The complete closed set of HealthKit platform source types in the version 0.2.0 catalog."
* ^experimental = false
* include codes from system HealthKitSourceTypeCS
