//
// This source file is part of the Grove FHIR open-source project
//
// SPDX-FileCopyrightText: 2026 Schmiedmayer Lab and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//
// GENERATED by tools/generate-platform-vocabulary.py — do not edit by hand.
// Regenerate from the framework's own values after changing any
// @SynthesizeDisplayProperty invocation in Grove; CI fails when the committed
// output differs from a fresh run.

CodeSystem: HealthkitAppleEcgAlgorithmVersionCS
Id: healthkit-apple-ecg-algorithm-version
Title: "HealthKit Apple ECG Algorithm Version"
Description: "Values of Apple HealthKit's `HKAppleECGAlgorithmVersion`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-apple-ecg-algorithm-version"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #version1 "version1"
* #version2 "version2"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitAppleWalkingSteadinessClassificationCS
Id: healthkit-apple-walking-steadiness-classification
Title: "HealthKit Apple Walking Steadiness Classification"
Description: "Values of Apple HealthKit's `HKAppleWalkingSteadinessClassification`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-apple-walking-steadiness-classification"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #ok "ok"
* #low "low"
* #veryLow "very low"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitBloodGlucoseMealTimeCS
Id: healthkit-blood-glucose-meal-time
Title: "HealthKit Blood Glucose Meal Time"
Description: "Values of Apple HealthKit's `HKBloodGlucoseMealTime`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-blood-glucose-meal-time"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #preprandial "preprandial"
* #postprandial "postprandial"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitBodyTemperatureSensorLocationCS
Id: healthkit-body-temperature-sensor-location
Title: "HealthKit Body Temperature Sensor Location"
Description: "Values of Apple HealthKit's `HKBodyTemperatureSensorLocation`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-body-temperature-sensor-location"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #other "other"
* #armpit "armpit"
* #body "body"
* #ear "ear"
* #finger "finger"
* #gastroIntestinal "gastro intestinal"
* #mouth "mouth"
* #rectum "rectum"
* #toe "toe"
* #earDrum "ear drum"
* #temporalArtery "temporal artery"
* #forehead "forehead"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueAppetiteChangesCS
Id: healthkit-category-value-appetite-changes
Title: "HealthKit Category Value Appetite Changes"
Description: "Values of Apple HealthKit's `HKCategoryValueAppetiteChanges`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-appetite-changes"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unspecified "unspecified"
* #noChange "no change"
* #decreased "decreased"
* #increased "increased"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueAppleStandHourCS
Id: healthkit-category-value-apple-stand-hour
Title: "HealthKit Category Value Apple Stand Hour"
Description: "Values of Apple HealthKit's `HKCategoryValueAppleStandHour`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-apple-stand-hour"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #stood "stood"
* #idle "idle"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueAppleWalkingSteadinessEventCS
Id: healthkit-category-value-apple-walking-steadiness-event
Title: "HealthKit Category Value Apple Walking Steadiness Event"
Description: "Values of Apple HealthKit's `HKCategoryValueAppleWalkingSteadinessEvent`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-apple-walking-steadiness-event"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #initialLow "initial low"
* #initialVeryLow "initial very low"
* #repeatLow "repeat low"
* #repeatVeryLow "repeat very low"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueCervicalMucusQualityCS
Id: healthkit-category-value-cervical-mucus-quality
Title: "HealthKit Category Value Cervical Mucus Quality"
Description: "Values of Apple HealthKit's `HKCategoryValueCervicalMucusQuality`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-cervical-mucus-quality"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #dry "dry"
* #sticky "sticky"
* #creamy "creamy"
* #watery "watery"
* #eggWhite "egg white"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueContraceptiveCS
Id: healthkit-category-value-contraceptive
Title: "HealthKit Category Value Contraceptive"
Description: "Values of Apple HealthKit's `HKCategoryValueContraceptive`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-contraceptive"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unspecified "unspecified"
* #implant "implant"
* #injection "injection"
* #intrauterineDevice "intrauterine device"
* #intravaginalRing "intravaginal ring"
* #oral "oral"
* #patch "patch"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueEnvironmentalAudioExposureEventCS
Id: healthkit-category-value-environmental-audio-exposure-event
Title: "HealthKit Category Value Environmental Audio Exposure Event"
Description: "Values of Apple HealthKit's `HKCategoryValueEnvironmentalAudioExposureEvent`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-environmental-audio-exposure-event"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #momentaryLimit "momentary limit"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueHeadphoneAudioExposureEventCS
Id: healthkit-category-value-headphone-audio-exposure-event
Title: "HealthKit Category Value Headphone Audio Exposure Event"
Description: "Values of Apple HealthKit's `HKCategoryValueHeadphoneAudioExposureEvent`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-headphone-audio-exposure-event"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #sevenDayLimit "seven day limit"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueLowCardioFitnessEventCS
Id: healthkit-category-value-low-cardio-fitness-event
Title: "HealthKit Category Value Low Cardio Fitness Event"
Description: "Values of Apple HealthKit's `HKCategoryValueLowCardioFitnessEvent`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-low-cardio-fitness-event"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #lowFitness "low fitness"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueMenstrualFlowCS
Id: healthkit-category-value-menstrual-flow
Title: "HealthKit Category Value Menstrual Flow"
Description: "Values of Apple HealthKit's `HKCategoryValueMenstrualFlow`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-menstrual-flow"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unspecified "unspecified"
* #light "light"
* #medium "medium"
* #heavy "heavy"
* #none "none"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueOvulationTestResultCS
Id: healthkit-category-value-ovulation-test-result
Title: "HealthKit Category Value Ovulation Test Result"
Description: "Values of Apple HealthKit's `HKCategoryValueOvulationTestResult`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-ovulation-test-result"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #negative "negative"
* #luteinizingHormoneSurge "luteinizing hormone surge"
* #indeterminate "indeterminate"
* #estrogenSurge "estrogen surge"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValuePregnancyTestResultCS
Id: healthkit-category-value-pregnancy-test-result
Title: "HealthKit Category Value Pregnancy Test Result"
Description: "Values of Apple HealthKit's `HKCategoryValuePregnancyTestResult`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-pregnancy-test-result"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #negative "negative"
* #positive "positive"
* #indeterminate "indeterminate"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValuePresenceCS
Id: healthkit-category-value-presence
Title: "HealthKit Category Value Presence"
Description: "Values of Apple HealthKit's `HKCategoryValuePresence`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-presence"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #present "present"
* #notPresent "not present"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueProgesteroneTestResultCS
Id: healthkit-category-value-progesterone-test-result
Title: "HealthKit Category Value Progesterone Test Result"
Description: "Values of Apple HealthKit's `HKCategoryValueProgesteroneTestResult`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-progesterone-test-result"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #negative "negative"
* #positive "positive"
* #indeterminate "indeterminate"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueSeverityCS
Id: healthkit-category-value-severity
Title: "HealthKit Category Value Severity"
Description: "Values of Apple HealthKit's `HKCategoryValueSeverity`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-severity"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unspecified "unspecified"
* #notPresent "not present"
* #mild "mild"
* #moderate "moderate"
* #severe "severe"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueSleepAnalysisCS
Id: healthkit-category-value-sleep-analysis
Title: "HealthKit Category Value Sleep Analysis"
Description: "Values of Apple HealthKit's `HKCategoryValueSleepAnalysis`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-sleep-analysis"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #inBed "in bed"
* #asleepUnspecified "asleep unspecified"
* #awake "awake"
* #asleepCore "asleep core"
* #asleepDeep "asleep deep"
* #asleepREM "asleep REM"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCategoryValueVaginalBleedingCS
Id: healthkit-category-value-vaginal-bleeding
Title: "HealthKit Category Value Vaginal Bleeding"
Description: "Values of Apple HealthKit's `HKCategoryValueVaginalBleeding`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-category-value-vaginal-bleeding"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unspecified "unspecified"
* #light "light"
* #medium "medium"
* #heavy "heavy"
* #none "none"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitCyclingFunctionalThresholdPowerTestTypeCS
Id: healthkit-cycling-functional-threshold-power-test-type
Title: "HealthKit Cycling Functional Threshold Power Test Type"
Description: "Values of Apple HealthKit's `HKCyclingFunctionalThresholdPowerTestType`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-cycling-functional-threshold-power-test-type"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #maxExercise60Minute "max exercise60 minute"
* #maxExercise20Minute "max exercise20 minute"
* #rampTest "ramp test"
* #predictionExercise "prediction exercise"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitDevicePlacementSideCS
Id: healthkit-device-placement-side
Title: "HealthKit Device Placement Side"
Description: "Values of Apple HealthKit's `HKDevicePlacementSide`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-device-placement-side"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unknown "unknown"
* #left "left"
* #right "right"
* #central "central"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitElectrocardiogramClassificationCS
Id: healthkit-electrocardiogram-classification
Title: "HealthKit Electrocardiogram Classification"
Description: "Values of Apple HealthKit's `HKElectrocardiogram.Classification`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-electrocardiogram-classification"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #notSet "not set"
* #sinusRhythm "sinus rhythm"
* #atrialFibrillation "atrial fibrillation"
* #inconclusiveLowHeartRate "inconclusive low heart rate"
* #inconclusiveHighHeartRate "inconclusive high heart rate"
* #inconclusivePoorReading "inconclusive poor reading"
* #inconclusiveOther "inconclusive other"
* #unrecognized "unrecognized"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitElectrocardiogramSymptomsStatusCS
Id: healthkit-electrocardiogram-symptoms-status
Title: "HealthKit Electrocardiogram Symptoms Status"
Description: "Values of Apple HealthKit's `HKElectrocardiogram.SymptomsStatus`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-electrocardiogram-symptoms-status"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #notSet "not set"
* #none "none"
* #present "present"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitHeartRateMotionContextCS
Id: healthkit-heart-rate-motion-context
Title: "HealthKit Heart Rate Motion Context"
Description: "Values of Apple HealthKit's `HKHeartRateMotionContext`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-heart-rate-motion-context"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #notSet "not set"
* #sedentary "sedentary"
* #active "active"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitHeartRateRecoveryTestTypeCS
Id: healthkit-heart-rate-recovery-test-type
Title: "HealthKit Heart Rate Recovery Test Type"
Description: "Values of Apple HealthKit's `HKHeartRateRecoveryTestType`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-heart-rate-recovery-test-type"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #maxExercise "max exercise"
* #predictionSubMaxExercise "prediction sub max exercise"
* #predictionNonExercise "prediction non exercise"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitHeartRateSensorLocationCS
Id: healthkit-heart-rate-sensor-location
Title: "HealthKit Heart Rate Sensor Location"
Description: "Values of Apple HealthKit's `HKHeartRateSensorLocation`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-heart-rate-sensor-location"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #other "other"
* #chest "chest"
* #wrist "wrist"
* #finger "finger"
* #hand "hand"
* #earLobe "ear lobe"
* #foot "foot"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitInsulinDeliveryReasonCS
Id: healthkit-insulin-delivery-reason
Title: "HealthKit Insulin Delivery Reason"
Description: "Values of Apple HealthKit's `HKInsulinDeliveryReason`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-insulin-delivery-reason"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #basal "basal"
* #bolus "bolus"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitPhysicalEffortEstimationTypeCS
Id: healthkit-physical-effort-estimation-type
Title: "HealthKit Physical Effort Estimation Type"
Description: "Values of Apple HealthKit's `HKPhysicalEffortEstimationType`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-physical-effort-estimation-type"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #activityLookup "activity lookup"
* #deviceSensed "device sensed"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitStateOfMindAssociationCS
Id: healthkit-state-of-mind-association
Title: "HealthKit State Of Mind Association"
Description: "Values of Apple HealthKit's `HKStateOfMind.Association`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-state-of-mind-association"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #community "community"
* #currentEvents "current events"
* #dating "dating"
* #education "education"
* #family "family"
* #fitness "fitness"
* #friends "friends"
* #health "health"
* #hobbies "hobbies"
* #identity "identity"
* #money "money"
* #partner "partner"
* #selfCare "self care"
* #spirituality "spirituality"
* #tasks "tasks"
* #travel "travel"
* #work "work"
* #weather "weather"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitStateOfMindKindCS
Id: healthkit-state-of-mind-kind
Title: "HealthKit State Of Mind Kind"
Description: "Values of Apple HealthKit's `HKStateOfMind.Kind`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-state-of-mind-kind"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #momentaryEmotion "momentary emotion"
* #dailyMood "daily mood"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitStateOfMindLabelCS
Id: healthkit-state-of-mind-label
Title: "HealthKit State Of Mind Label"
Description: "Values of Apple HealthKit's `HKStateOfMind.Label`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-state-of-mind-label"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #amazed "amazed"
* #amused "amused"
* #angry "angry"
* #anxious "anxious"
* #ashamed "ashamed"
* #brave "brave"
* #calm "calm"
* #content "content"
* #disappointed "disappointed"
* #discouraged "discouraged"
* #disgusted "disgusted"
* #embarrassed "embarrassed"
* #excited "excited"
* #frustrated "frustrated"
* #grateful "grateful"
* #guilty "guilty"
* #happy "happy"
* #hopeless "hopeless"
* #irritated "irritated"
* #jealous "jealous"
* #joyful "joyful"
* #lonely "lonely"
* #passionate "passionate"
* #peaceful "peaceful"
* #proud "proud"
* #relieved "relieved"
* #sad "sad"
* #scared "scared"
* #stressed "stressed"
* #surprised "surprised"
* #worried "worried"
* #annoyed "annoyed"
* #confident "confident"
* #drained "drained"
* #hopeful "hopeful"
* #indifferent "indifferent"
* #overwhelmed "overwhelmed"
* #satisfied "satisfied"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitStateOfMindValenceClassificationCS
Id: healthkit-state-of-mind-valence-classification
Title: "HealthKit State Of Mind Valence Classification"
Description: "Values of Apple HealthKit's `HKStateOfMind.ValenceClassification`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-state-of-mind-valence-classification"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #veryUnpleasant "very unpleasant"
* #unpleasant "unpleasant"
* #slightlyUnpleasant "slightly unpleasant"
* #neutral "neutral"
* #slightlyPleasant "slightly pleasant"
* #pleasant "pleasant"
* #veryPleasant "very pleasant"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitSwimmingStrokeStyleCS
Id: healthkit-swimming-stroke-style
Title: "HealthKit Swimming Stroke Style"
Description: "Values of Apple HealthKit's `HKSwimmingStrokeStyle`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-swimming-stroke-style"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unknown "unknown"
* #mixed "mixed"
* #freestyle "freestyle"
* #backstroke "backstroke"
* #breaststroke "breaststroke"
* #butterfly "butterfly"
* #kickboard "kickboard"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitUserMotionContextCS
Id: healthkit-user-motion-context
Title: "HealthKit User Motion Context"
Description: "Values of Apple HealthKit's `HKUserMotionContext`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-user-motion-context"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #notSet "not set"
* #stationary "stationary"
* #active "active"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitVo2MaxTestTypeCS
Id: healthkit-vo2-max-test-type
Title: "HealthKit VO2 Max Test Type"
Description: "Values of Apple HealthKit's `HKVO2MaxTestType`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-vo2-max-test-type"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #maxExercise "max exercise"
* #predictionSubMaxExercise "prediction sub max exercise"
* #predictionNonExercise "prediction non exercise"
* #predictionStepTest "prediction step test"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitWaterSalinityCS
Id: healthkit-water-salinity
Title: "HealthKit Water Salinity"
Description: "Values of Apple HealthKit's `HKWaterSalinity`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-water-salinity"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #freshWater "fresh water"
* #saltWater "salt water"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitWeatherConditionCS
Id: healthkit-weather-condition
Title: "HealthKit Weather Condition"
Description: "Values of Apple HealthKit's `HKWeatherCondition`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-weather-condition"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #none "none"
* #clear "clear"
* #fair "fair"
* #partlyCloudy "partly cloudy"
* #mostlyCloudy "mostly cloudy"
* #cloudy "cloudy"
* #foggy "foggy"
* #haze "haze"
* #windy "windy"
* #blustery "blustery"
* #smoky "smoky"
* #dust "dust"
* #snow "snow"
* #hail "hail"
* #sleet "sleet"
* #freezingDrizzle "freezing drizzle"
* #freezingRain "freezing rain"
* #mixedRainAndHail "mixed rain and hail"
* #mixedRainAndSnow "mixed rain and snow"
* #mixedRainAndSleet "mixed rain and sleet"
* #mixedSnowAndSleet "mixed snow and sleet"
* #drizzle "drizzle"
* #scatteredShowers "scattered showers"
* #showers "showers"
* #thunderstorms "thunderstorms"
* #tropicalStorm "tropical storm"
* #hurricane "hurricane"
* #tornado "tornado"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitWorkoutSwimmingLocationTypeCS
Id: healthkit-workout-swimming-location-type
Title: "HealthKit Workout Swimming Location Type"
Description: "Values of Apple HealthKit's `HKWorkoutSwimmingLocationType`, coded by their Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-workout-swimming-location-type"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #unknown "unknown"
* #pool "pool"
* #openWater "open water"
* #unrecognized-platform-value "unrecognized platform value" "Grove's code, not Apple's: the platform reported a value the writing build did not recognize. Several of these enumerations declare an `unknown` case of their own."


CodeSystem: HealthkitElectrocardiogramPropertyCS
Id: healthkit-electrocardiogram-property
Title: "HealthKit Electrocardiogram Properties"
Description: "Component codes of an electrocardiogram observation."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-electrocardiogram-property"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #classification "Electrocardiogram Classification"
* #symptoms-status "Electrocardiogram Symptoms Status"
* #number-of-voltage-measurements "Electrocardiogram Number of Voltage Measurements"
* #sampling-frequency "Sampling Frequency"


CodeSystem: HealthkitStateOfMindPropertyCS
Id: healthkit-state-of-mind-property
Title: "HealthKit State of Mind Properties"
Description: "Component codes of a state-of-mind observation."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-state-of-mind-property"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #kind "State of Mind Kind"
* #valence "State of Mind Valence"
* #valence-classification "State of Mind Valence Classification"
* #label "State of Mind Label"
* #association "State of Mind Association"


CodeSystem: HealthkitWorkoutActivityTypeCS
Id: healthkit-workout-activity-type
Title: "HealthKit Workout Activity Types"
Description: "Apple HealthKit's `HKWorkoutActivityType`, coded by its Swift case names."
* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/healthkit-workout-activity-type"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* #americanFootball "american football"
* #archery "archery"
* #australianFootball "australian football"
* #badminton "badminton"
* #barre "barre"
* #baseball "baseball"
* #basketball "basketball"
* #bowling "bowling"
* #boxing "boxing"
* #cardioDance "cardio dance"
* #climbing "climbing"
* #cooldown "cooldown"
* #coreTraining "core training"
* #cricket "cricket"
* #crossCountrySkiing "cross country skiing"
* #crossTraining "cross training"
* #curling "curling"
* #cycling "cycling"
* #dance "dance"
* #danceInspiredTraining "dance inspired training"
* #discSports "disc sports"
* #downhillSkiing "downhill skiing"
* #elliptical "elliptical"
* #equestrianSports "equestrian sports"
* #fencing "fencing"
* #fishing "fishing"
* #fitnessGaming "fitness gaming"
* #flexibility "flexibility"
* #functionalStrengthTraining "functional strength training"
* #golf "golf"
* #gymnastics "gymnastics"
* #handCycling "hand cycling"
* #handball "handball"
* #highIntensityIntervalTraining "high intensity interval training"
* #hiking "hiking"
* #hockey "hockey"
* #hunting "hunting"
* #jumpRope "jump rope"
* #kickboxing "kickboxing"
* #lacrosse "lacrosse"
* #martialArts "martial arts"
* #mindAndBody "mind and body"
* #mixedCardio "mixed cardio"
* #mixedMetabolicCardioTraining "mixed metabolic cardio training"
* #other "other"
* #paddleSports "paddle sports"
* #pickleball "pickleball"
* #pilates "pilates"
* #play "play"
* #preparationAndRecovery "preparation and recovery"
* #racquetball "racquetball"
* #rowing "rowing"
* #rugby "rugby"
* #running "running"
* #sailing "sailing"
* #skatingSports "skating sports"
* #snowboarding "snowboarding"
* #snowSports "snow sports"
* #soccer "soccer"
* #socialDance "social dance"
* #softball "softball"
* #squash "squash"
* #stairClimbing "stair climbing"
* #stairs "stairs"
* #stepTraining "step training"
* #surfingSports "surfing sports"
* #swimBikeRun "swim bike run"
* #swimming "swimming"
* #tableTennis "table tennis"
* #taiChi "tai chi"
* #tennis "tennis"
* #trackAndField "track and field"
* #traditionalStrengthTraining "traditional strength training"
* #transition "transition"
* #underwaterDiving "underwater diving"
* #volleyball "volleyball"
* #walking "walking"
* #waterFitness "water fitness"
* #waterPolo "water polo"
* #waterSports "water sports"
* #wheelchairRunPace "wheelchair run pace"
* #wheelchairWalkPace "wheelchair walk pace"
* #wrestling "wrestling"
* #yoga "yoga"
