#!/usr/bin/env python3
#
# This source file is part of the Grove FHIR open-source project
#
# SPDX-FileCopyrightText: 2026 Schmiedmayer Lab and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

"""Generates the platform-vocabulary FSH from the values Grove itself writes.

The vocabulary must never drift from what the framework emits, so the enumerated code
systems are not derived here at all: the Swift test target dumps every type's
`fhirSystemName`, `fhirSystemTitle` and `fhirPublishedCodes` — the same members the
`@SynthesizeDisplayProperty` macro synthesizes the runtime `code` and `display` from —
and this script publishes that dump verbatim. Produce it with

    GROVE_VOCABULARY_DUMP=/tmp/grove-vocabulary.json \
        swift test --filter PlatformVocabularyDumpTests

then run

    tools/generate-platform-vocabulary.py --grove <Grove checkout> --dump /tmp/grove-vocabulary.json

It rewrites platforms/input/fsh/generated-healthkit-values.fsh and the generated block
of platforms/input/ignoreWarnings.txt in place; CI fails if either differs from what is
committed.
"""
import argparse
import json
import pathlib
import re
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "platforms" / "input" / "fsh"

# Systems whose codes are Coding literals rather than macro-synthesized: the property
# codes naming an observation's components, and the workout activity types.
LITERAL_SOURCES = [
    ("healthKitECGProperty",
     "Sources/GroveHealthKitFHIR/Sample Type FHIR Mapping/ECGTypeFHIRMapping.swift",
     "healthkit-electrocardiogram-property",
     "HealthKit Electrocardiogram Properties",
     "Component codes of an electrocardiogram observation."),
    ("healthKitStateOfMindProperty",
     "Sources/GroveHealthKitFHIR/Sample Type FHIR Mapping/StateOfMindTypeFHIRMapping.swift",
     "healthkit-state-of-mind-property",
     "HealthKit State of Mind Properties",
     "Component codes of a state-of-mind observation."),
]

WORKOUT_SOURCE = "Sources/GroveHealthKitFHIR/HealthKit2FHIR/HKWorkout+Observation.swift"
KEY_SPACES = OUT / "key-spaces.fsh"

SUPPRESSIONS_BEGIN = "# --- generated by tools/generate-platform-vocabulary.py; do not edit below ---"
SUPPRESSIONS_END = "# --- end generated ---"

# The sentinel the framework writes for a value it does not recognize. Every generated
# system defines it, which is what keeps those systems complete.
UNRECOGNIZED_CODE = "unrecognized-platform-value"
UNRECOGNIZED_DEFINITION = (
    "Grove's code, not Apple's: the platform reported a value the writing build did not "
    "recognize. Several of these enumerations declare an `unknown` case of their own.")


def class_name(system: str) -> str:
    return system.replace("-", " ").title().replace(" ", "") + "CS"


def workout_display(case_name: str) -> str:
    """A readable display for a workout activity code.

    The framework writes no display for these — only the code — so this is the one
    spelling in the file that cannot disagree with anything Grove emits.
    """
    parts = re.findall(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+", case_name)
    return " ".join(p if p.isupper() else p.lower() for p in parts)


def literal_codes(grove: pathlib.Path, vocabulary_name: str, relative: str):
    """The `Coding(code:display:system:)` literals the framework writes for one system."""
    source = (grove / relative).read_text()
    pattern = re.compile(
        r'Coding\(\s*code:\s*"([^"]+)",\s*display:\s*"([^"]+)",\s*'
        r"system:\s*GroveFHIRVocabulary\." + vocabulary_name + r"\b", re.S)
    return [(match.group(1), match.group(2)) for match in pattern.finditer(source)]


def workout_activity_types(grove: pathlib.Path):
    """The workout activity codes, read from the switch that writes them."""
    source = (grove / WORKOUT_SOURCE).read_text()
    body = source[source.index("var fhirWorkoutTypeValue"):]
    return [(code, workout_display(code)) for code in re.findall(r'return\s+"(\w+)"', body)]


def code_system(system: str, title_text: str, description: str, codes):
    lines = [
        f"CodeSystem: {class_name(system)}",
        f"Id: {system}",
        f'Title: "{title_text}"',
        f'Description: "{description}"',
        f'* ^url = "https://grovealliance.org/fhir/platforms/CodeSystem/{system}"',
        "* ^experimental = false",
        "* ^caseSensitive = true",
        "* ^content = #complete",
    ]
    for code, text in codes:
        definition = f' "{UNRECOGNIZED_DEFINITION}"' if code == UNRECOGNIZED_CODE else ""
        lines.append(f'* #{code} "{text}"{definition}')
    return lines + ["", ""]


def published_metadata_keys() -> list[str]:
    """The `healthkit-metadata-key` codes the guide publishes."""
    codes, inside = [], False
    for line in KEY_SPACES.read_text().splitlines():
        if line.startswith("Id:"):
            inside = line.split(":", 1)[1].strip() == "healthkit-metadata-key"
        elif inside and line.startswith("* #"):
            codes.append(line[3:].split(" ", 1)[0])
    return codes


def check_metadata_keys(dump) -> bool:
    """The metadata keys are hand-written, so pin them to the ones the framework writes."""
    published, written = set(published_metadata_keys()), set(dump["metadataKeys"])
    for code in sorted(written - published):
        print(f"{KEY_SPACES.name} is missing the metadata key Grove writes: {code}", file=sys.stderr)
    for code in sorted(published - written):
        print(f"{KEY_SPACES.name} publishes a metadata key Grove never writes: {code}", file=sys.stderr)
    return published == written


def write_suppressions() -> None:
    """The OID warning fires once per code system, so that block is generated too."""
    path = OUT.parent / "ignoreWarnings.txt"
    kept, generated = [], False
    for line in path.read_text().splitlines() if path.exists() else ["== Suppressed Messages ==", ""]:
        if line == SUPPRESSIONS_BEGIN:
            generated = True
        elif line == SUPPRESSIONS_END:
            generated = False
        elif not generated:
            kept.append(line)
    if not kept or not kept[0].startswith("== Suppressed Messages =="):
        kept.insert(0, "== Suppressed Messages ==")
    while kept and not kept[-1].strip():
        kept.pop()

    # Every terminology resource the guide defines draws the warning once, so the block
    # is keyed by the artefact kind the FSH declares, not by CodeSystem alone.
    resources = set()
    for path_ in OUT.glob("*.fsh"):
        kind = None
        for line in path_.read_text().splitlines():
            if line.startswith("CodeSystem:"):
                kind = "CodeSystem"
            elif line.startswith("ValueSet:"):
                kind = "ValueSet"
            elif line.startswith("Id:") and kind:
                resources.add((kind, line.split(":", 1)[1].strip()))
                kind = None
    oid_warning = (
        "should have an OID assigned to cater for possible use with OID based terminology "
        "systems e.g. CDA usage (OIDs are easy to assign - see "
        "https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html"
        "#ig-parameters-auto-oid-root)")
    path.write_text("\n".join(kept + [
        "",
        SUPPRESSIONS_BEGIN,
        "# Grove has no CDA or OID-based exchange touchpoint; OIDs can be assigned via",
        "# auto-oid-root before a milestone publication if ever needed.",
    ] + [
        f"The resource {kind}/{identifier} {oid_warning}" for kind, identifier in sorted(resources)
    ] + [SUPPRESSIONS_END]) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--grove", required=True, type=pathlib.Path,
                        help="path to the Grove framework checkout")
    parser.add_argument("--dump", required=True, type=pathlib.Path,
                        help="path to the JSON written by PlatformVocabularyDumpTests")
    arguments = parser.parse_args()
    dump = json.loads(arguments.dump.read_text())

    # These strings deliberately place the SPDX header in the generated FSH file.
    # REUSE-IgnoreStart
    lines = [
        "//",
        "// This source file is part of the Grove FHIR open-source project",
        "//",
        "// SPDX-FileCopyrightText: 2026 Schmiedmayer Lab and the project authors (see CONTRIBUTORS.md)",
        "//",
        "// SPDX-License-Identifier: MIT",
        "//",
        "// GENERATED by tools/generate-platform-vocabulary.py — do not edit by hand.",
        "// Regenerate from the framework's own values after changing any",
        "// @SynthesizeDisplayProperty invocation in Grove; CI fails when the committed",
        "// output differs from a fresh run.",
        "",
    ]
    # REUSE-IgnoreEnd
    seen = set()
    for entry in sorted(dump["codeSystems"], key=lambda entry: entry["system"]):
        system = entry["system"]
        if system in seen:
            raise SystemExit(f"duplicate code system {system} (from {entry['type']})")
        seen.add(system)
        lines += code_system(
            system, entry["title"],
            f"Values of Apple HealthKit's `{entry['type']}`, coded by their Swift case names.",
            [(concept["code"], concept["display"]) for concept in entry["concepts"]])

    for vocabulary_name, relative, system, title_text, description in LITERAL_SOURCES:
        codes = literal_codes(arguments.grove, vocabulary_name, relative)
        if not codes:
            raise SystemExit(f"no codes found for {system} in {relative}")
        seen.add(system)
        lines += code_system(system, title_text, description, codes)

    seen.add("healthkit-workout-activity-type")
    lines += code_system(
        "healthkit-workout-activity-type",
        "HealthKit Workout Activity Types",
        "Apple HealthKit's `HKWorkoutActivityType`, coded by its Swift case names.",
        workout_activity_types(arguments.grove))

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "generated-healthkit-values.fsh").write_text("\n".join(lines).rstrip() + "\n")
    write_suppressions()
    print(f"generated {len(seen)} code systems")
    return 0 if check_metadata_keys(dump) else 1


if __name__ == "__main__":
    raise SystemExit(main())
