#
# This source file is part of the Grove FHIR open-source project
#
# SPDX-FileCopyrightText: 2026 Schmiedmayer Lab and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Repository Standards

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  standards:
    name: Standards
    uses: SchmiedmayerLab/.github/.github/workflows/repository-standards.yml@v0.5
    with:
      runs_on_labels: '["blacksmith-4vcpu-ubuntu-2404"]'
    permissions:
      contents: read
      pull-requests: read
